<?php
/** @var $block \Bitpay\BPCheckout\Block\Index */
$configValue = $block->getBaseSecureUrl();
$env = $block->getBitpayEnv();
$order_id = $block->getOrderId();
?>
<h2 id="bitpay-header">Thank you for your purchase.</h2>
<div id="success-bitpay-page">
    <?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
    <div class="checkout-success">
        <?php if ($order_id): ?>
            <p><?= /* @noEscape */ __('Your order # is: <b>' . $order_id . '</b> ') ?></p>
            <p>
                <?= /* @noEscape */ __('We\'ll email you an order confirmation with details and tracking info. ') ?>
            </p>
        <?php endif; ?>

        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue"
                    href="/"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<!--end page to show with redirect-->
