<?php /** @var $block \Bitpay\BPCheckout\Block\Checkout\Onepage\Success\PayButton */ ?>
<?php if ($block->getOrderId() && $block->canViewPayButton()) :?>
<div>
    <br/>
    <a href="<?= $block->escapeUrl($block->getButtonUrl()) ?>" title="<?= $block->escapeHtml(__('Pay with BitPay')) ?>">
        <img src="<?php echo $block->getViewFileUrl('Bitpay_BPCheckout::images/Pay-with-BitPay-CardGroup.svg'); ?>" alt="<?= $block->escapeHtml(__('Pay with BitPay')) ?>" />
    </a>
</div>
<?php endif; ?>
