name: Test

on: [push, pull_request]

env:
  NODE_VERSION: 18

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run linter
        run: |
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require magento/magento-coding-standard --dev
          cd vendor/magento/magento-coding-standard
          npm install
          npm run eslint -- ../../../view
